name: 'Mise Step Optional'
description: 'Run a mise task if it exists'
inputs:
  mise-task:
    description: 'The mise task to conditionally execute'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check ${{ inputs.mise-task }} existence
      id: check_step
      env:
        MISE_TASK: ${{ inputs.mise-task }}
      run: |
        if mise tasks "$MISE_TASK" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Run ${{ inputs.mise-task }}
      if: ${{ steps.check_step.outputs.exists == 'true' }}
      env:
        MISE_TASK: ${{ inputs.mise-task }}
      run: |
        echo "/////////////////////////////////////"
        echo "//// Running ${MISE_TASK}"
        echo "/////////////////////////////////////"
        mise run "$MISE_TASK"
      shell: bash