name: "Deploy On Chromatic"
description: "Deploy your app to Chromatic for visual regression testing. This action uses Make for linting, building, testing, and packaging, then publishes Storybook to Chromatic."
inputs:
  artifact-name:
    description: "Name for the uploaded artifact, leave empty if no artifact is needed"
    required: false
  artifact-path:
    description: "Path to the artifact to upload, leave empty if no artifact is needed"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: storybook-static
        path: ./storybook-static
    - name: Publish to Chromatic
      id: chromatic
      uses: chromaui/action@latest
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        storybookBuildDir: ./storybook-static

    - name: Chromatic Footer
      shell: bash
      run: |
        echo "## Deployed to Chromatic" >> $GITHUB_STEP_SUMMARY
        echo ""  >> $GITHUB_STEP_SUMMARY
        echo "Report: ${{ steps.chromatic.outputs.buildUrl }}" >> $GITHUB_STEP_SUMMARY
        echo ""  >> $GITHUB_STEP_SUMMARY
        echo "Preview: ${{ steps.chromatic.outputs.storybookUrl }}" >> $GITHUB_STEP_SUMMARY
