name: "Node.js Environment Setup and Dependency Caching"
description: "This workflow sets up a Node.js environment with automatic package manager detection (yarn/pnpm/npm), caches dependencies, and configures authentication for private NPM packages."
inputs:
  base-dir:
    description: "Base directory of the Node.js project, if applicable."
    required: false
    default: ""
  node-version:
    description: "The version of Node.js to be installed."
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Detect package manager
      id: detect-package-manager
      shell: bash
      run: |
        if [[ "${{ inputs.base-dir }}" != "" ]]; then
          base_dir="${{ inputs.base-dir }}"
        else
          base_dir="."
        fi
        
        if [ -f "$base_dir/pnpm-lock.yaml" ]; then
          echo "package-manager=pnpm" >> $GITHUB_OUTPUT
          echo "lockfile=pnpm-lock.yaml" >> $GITHUB_OUTPUT
        elif [ -f "$base_dir/yarn.lock" ]; then
          echo "package-manager=yarn" >> $GITHUB_OUTPUT
          echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
        elif [ -f "$base_dir/package-lock.json" ]; then
          echo "package-manager=npm" >> $GITHUB_OUTPUT
          echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
        else
          echo "package-manager=yarn" >> $GITHUB_OUTPUT
          echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
        fi

    - if: inputs.base-dir != ''
      name: Setup Node with base-dir ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ steps.detect-package-manager.outputs.package-manager }}
        cache-dependency-path: ${{ github.workspace }}/${{ inputs.base-dir }}/${{ steps.detect-package-manager.outputs.lockfile }}

    - if: inputs.base-dir == ''
      name: Setup Node without base-dir ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ steps.detect-package-manager.outputs.package-manager }}

    - if: steps.detect-package-manager.outputs.package-manager == 'pnpm'
      name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - if: steps.detect-package-manager.outputs.package-manager == 'yarn'
      uses: actions/cache@v4
      id: yarn-modules-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-yarn-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-modules-

    - if: steps.detect-package-manager.outputs.package-manager == 'pnpm'
      uses: actions/cache@v4
      id: pnpm-modules-cache
      with:
        path: |
          ~/.pnpm-store
          **/node_modules
        key: ${{ runner.os }}-pnpm-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-modules-

    - if: steps.detect-package-manager.outputs.package-manager == 'npm'
      uses: actions/cache@v4
      id: npm-modules-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-npm-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-modules-

    - if: steps.detect-package-manager.outputs.package-manager == 'yarn'
      uses: actions/cache@v4
      id: yarn-dist-cache
      with:
        path: "**/dist"
        key: ${{ runner.os }}-yarn-dist-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-dist-

    - if: steps.detect-package-manager.outputs.package-manager == 'pnpm'
      uses: actions/cache@v4
      id: pnpm-dist-cache
      with:
        path: "**/dist"
        key: ${{ runner.os }}-pnpm-dist-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-dist-

    - if: steps.detect-package-manager.outputs.package-manager == 'npm'
      uses: actions/cache@v4
      id: npm-dist-cache
      with:
        path: "**/dist"
        key: ${{ runner.os }}-npm-dist-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-dist-
