name: "Make Actions"
description: "Run lint, build, test, and package commands using make"
inputs:
  base-dir:
    description: "Base directory of node project"
    required: false
    default: ""
  node-version:
    description: "Node version"
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    - if: inputs.base-dir != ''
      name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
        cache-dependency-path: ${{github.workspace}}/${{ inputs.base-dir }}/yarn.lock
    - if: inputs.base-dir == ''
      name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
    - uses: actions/cache@v4
      id: yarn-modules-cache # use this to check for `cache-hit` (`steps.yarn-modules-cache.outputs.cache-hit != 'true'`)   with:
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-yarn-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-modules-
    - uses: actions/cache@v4
      id: yarn-dist-cache # use this to check for `cache-hit` (`steps.yarn-dist-cache.outputs.cache-hit != 'true'`)   with:
      with:
        path: "**/dist"
        key: ${{ runner.os }}-yarn-dist-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-dist-
