name: "Get Version"
description: ""
inputs:
  use-snapshot:
    description: "Base directory of the Node.js project, if applicable."
    required: false
    default: "true"
  with-snapshot-sha:
    description: "Base directory of the Node.js project, if applicable."
    required: false
    default: ".${GITHUB_SHA:0:7}"
outputs:
  VERSION:
    description: "The path to the generated init.gradle.kts file"
    value: ${{ steps.version.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - name: Replace SNAPSHOT for specific branches
      if: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/release/') }}
      run: |
        VERSION=$(cat VERSION)
        VERSION=${VERSION/-SNAPSHOT/-dev-SNAPSHOT}
        echo "$VERSION" > VERSION
      shell: bash
    - name: Replace -SNAPSHOT with ${{ inputs.with-snapshot-sha }}
      if: inputs.use-snapshot == 'false'
      shell: bash
      run: |
        VERSION=$(cat VERSION)
        VERSION=${VERSION/-SNAPSHOT/${{ inputs.with-snapshot-sha }}}
        echo "$VERSION" > VERSION
    - name: Version
      id: version
      run: |
        if [ -f VERSION ]; then
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"
        else
          echo "Error: VERSION file not found." >&2
          exit 1
        fi
      shell: bash
    - name: Version Footer
      shell: bash
      run: |
        echo "## Project Version Information" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -z "${{ steps.version.outputs.VERSION }}" ]; then
          echo "The VERSION file could not be found, or it's empty. Unable to retrieve the version information." >> $GITHUB_STEP_SUMMARY
        else
          echo "The project is being built with the following version:" >> $GITHUB_STEP_SUMMARY
          echo "* **Version:** ${{ steps.version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
        fi