name: "Get Version"
description: ""
inputs:
  use-snapshot:
    description: "Base directory of the Node.js project, if applicable."
    required: false
    default: "true"
outputs:
  setup_gradle_github_pkg:
    description: "The path to the generated init.gradle.kts file"
    value: ${{ steps.version.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - name: Version
      id: version
      run: |
        if [ -f VERSION ]; then
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          echo "Error: VERSION file not found." >&2
          exit 1
        fi
      shell: bash
    - name: Replace SNAPSHOT for specific branches
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        if [[ "$BRANCH_NAME" != "main" && "$BRANCH_NAME" != release/* ]]; then
          VERSION=${VERSION/-SNAPSHOT/-dev-SNAPSHOT}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=VERSION::$VERSION"
        fi

      shell: bash
    - name: Replace -SNAPSHOT with +SHA
      if: inputs.use-snapshot == 'false'
      shell: bash
      run: |
        SHORT_SHA=${GITHUB_SHA:0:7}
        VERSION=${VERSION/-SNAPSHOT/+$SHORT_SHA}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=VERSION::$VERSION"

    - name: Version Footer
      shell: bash
      run: |
        echo "## Project Version Information" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -z "${{ steps.version.outputs.VERSION }}" ]; then
          echo "The VERSION file could not be found, or it's empty. Unable to retrieve the version information." >> $GITHUB_STEP_SUMMARY
        else
          echo "The project is being built with the following version:" >> $GITHUB_STEP_SUMMARY
          echo "* **Version:** ${{ steps.version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
        fi