name: "Mise Step PrePost"
description: "Run commands using mise, including optional pre and post steps"
inputs:
  mise-task:
    description: "The base mise task to execute along with its optional pre and post tasks"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run ${{ inputs.mise-task }}:pre optionally
      uses: komune-io/fixers-gradle/.github/actions/mise-step-optional@0.37.0
      with:
        mise-task: ${{ inputs.mise-task }}:pre

    - name: Run ${{ inputs.mise-task }} optionally
      uses: komune-io/fixers-gradle/.github/actions/mise-step-optional@0.37.0
      with:
        mise-task: ${{ inputs.mise-task }}

    - name: Run ${{ inputs.mise-task }}:post optionally
      uses: komune-io/fixers-gradle/.github/actions/mise-step-optional@0.37.0
      with:
        mise-task: ${{ inputs.mise-task }}:post