package io.komune.fixers.gradle.integration

import java.io.File
import java.nio.file.Path
import org.gradle.testkit.runner.BuildResult
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.io.TempDir

/**
 * Base class for integration tests that test plugins in real projects.
 * This class provides utilities for creating test projects and running Gradle tasks.
 */
abstract class BaseIntegrationTest {

    companion object {
        /**
         * Command-line argument for detailed stack traces in Gradle builds.
         */
        private const val STACKTRACE_ARG = "--stacktrace"

        /**
         * Kotlin version applied to the throwaway projects generated by these tests.
         * Tests always run against the Gradle version embedded in the TestKit runner,
         * so a single version is enough.
         */
        const val TEST_KOTLIN_VERSION = "2.3.0"
    }

    /**
     * Temporary directory for the test project.
     */
    @TempDir
    lateinit var testProjectDir: Path

    /**
     * The build.gradle.kts file of the test project.
     */
    protected lateinit var buildFile: File

    /**
     * The settings.gradle.kts file of the test project.
     */
    protected lateinit var settingsFile: File

    /**
     * The gradle.properties file of the test project.
     */
    protected lateinit var propertiesFile: File

    /**
     * Set up the test project with basic files.
     */
    @BeforeEach
    fun setup() {
        buildFile = testProjectDir.resolve("build.gradle.kts").toFile()
        settingsFile = testProjectDir.resolve("settings.gradle.kts").toFile()
        propertiesFile = testProjectDir.resolve("gradle.properties").toFile()

        // Create basic settings file
        settingsFile.writeText("""
            rootProject.name = "integration-test-project"
        """.trimIndent())

        // Create basic properties file
        propertiesFile.writeText("""
            kotlin.code.style=official
        """.trimIndent())
    }

    /**
     * Write content to the build.gradle.kts file.
     */
    protected fun writeBuildFile(content: String) {
        buildFile.writeText(content)
    }

    /**
     * Create a file in the test project.
     */
    protected fun createFile(relativePath: String, content: String): File {
        val file = testProjectDir.resolve(relativePath).toFile()
        file.parentFile.mkdirs()
        file.writeText(content)
        return file
    }

    /**
     * Run a Gradle build with the specified arguments.
     *
     * @param arguments The Gradle arguments to pass.
     * @return The build result.
     */
    protected fun runGradle(vararg arguments: String): BuildResult {
        val runner = GradleRunner.create()
            .withProjectDir(testProjectDir.toFile())
            .withArguments(*arguments, STACKTRACE_ARG)
            .withPluginClasspath()
            .forwardOutput()

        return runner.build()
    }

    /**
     * Run a Gradle build that is expected to fail.
     *
     * @param arguments The Gradle arguments to pass.
     * @return The build result.
     */
    protected fun runGradleAndFail(vararg arguments: String): BuildResult {
        val runner = GradleRunner.create()
            .withProjectDir(testProjectDir.toFile())
            .withArguments(*arguments, STACKTRACE_ARG)
            .withPluginClasspath()
            .forwardOutput()

        return runner.buildAndFail()
    }
}
