# This is a reusable GitHub Action defined in make-step-optional/action.yml

name: 'Make Step Optional'
description: 'Run a Makefile step if it exists'
inputs:
  make-file:
    description: 'The Makefile to use'
    required: true
  make-step:
    description: 'The make step to conditionally execute'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check ${{ inputs.make-step }} existence
      id: check_step
      env:
        MAKE_FILE: ${{ inputs.make-file }}
        MAKE_STEP: ${{ inputs.make-step }}
      run: |
        if grep -q "^${MAKE_STEP}:" "$MAKE_FILE"; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Run ${{ inputs.make-step }}
      if: ${{ steps.check_step.outputs.exists == 'true' }}
      env:
        MAKE_FILE: ${{ inputs.make-file }}
        MAKE_STEP: ${{ inputs.make-step }}
      run: |
        echo "/////////////////////////////////////"
        echo "//// Running ${MAKE_STEP}"
        echo "/////////////////////////////////////"
        make -f "$MAKE_FILE" "$MAKE_STEP"
      shell: bash
