name: 'Configure Gradle with GitHub Packages'
description: 'Configures Gradle to use a GitHub Packages repository for dependencies.'
outputs:
  setup_gradle_github_pkg:
    description: "The path to the generated init.gradle.kts file"
    value: ${{ steps.set_output.outputs.setup_gradle_github_pkg }}
runs:
  using: "composite"
  steps:
    - id: setup_gradle
      run: |
        mkdir -p ~/.gradle
        echo "settingsEvaluated {
            pluginManagement {
                repositories {
                    mavenCentral()
                    gradlePluginPortal()
                    maven {
                        url = uri(\"https://maven.pkg.github.com/komune-io/fixers\")
                        credentials {
                            username = System.getenv(\"PKG_GITHUB_USERNAME\")
                            password = System.getenv(\"PKG_GITHUB_TOKEN\")
                        }
                    }
                }
            }
        }
        allprojects {
            repositories {
                mavenCentral()
                maven {
                    url = uri(\"https://maven.pkg.github.com/komune-io/fixers\")
                    credentials {
                        username = System.getenv(\"PKG_GITHUB_USERNAME\")
                        password = System.getenv(\"PKG_GITHUB_TOKEN\")
                    }
                }
            }
        }" > ~/.gradle/init.gradle.kts
      shell: bash
    - id: set_output
      run: echo "setup_gradle_github_pkg=${HOME}/.gradle/init.gradle.kts" >> $GITHUB_OUTPUT
      shell: bash
