name: Example Workflow

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "The workflow ran on a pull request event."