name: Reusable Dev Workflow

on:
  workflow_call:
    inputs: # Define any inputs here if needed, for example, java version or branch name
      javaVersion:
        description: 'Java version'
        required: false
        type: 'string'
        default: '17'
    secrets:
      GPG_SIGNING_KEY:
        required: true
      GPG_SIGNING_PASSWORD:
        required: true
      PKG_MAVEN_USERNAME:
        required: true
      PKG_MAVEN_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
      PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Setup Maven Github Pkg
        run: |
          echo "settingsEvaluated {
              pluginManagement {
                  repositories {
                      gradlePluginPortal()
                      maven {
                          url = uri(\"https://maven.pkg.github.com/komune-io/fixers\")
                          credentials {
                              username = System.getenv(\"PKG_MAVEN_USERNAME\")
                              password = System.getenv(\"PKG_MAVEN_TOKEN\")
                          }
                      }
                  }
              }
          }
          
          allprojects {
              repositories {
                  mavenLocal()
                  mavenCentral()
                  maven {
                      url = uri(\"https://maven.pkg.github.com/komune-io/fixers\")
                      credentials {
                          username = System.getenv(\"PKG_MAVEN_USERNAME\")
                          password = System.getenv(\"PKG_MAVEN_TOKEN\")
                      }
                  }
              }
          }" > ~/.gradle/init.gradle.kts

      - name: Lint
        run: |
          cat ~/.gradle/init.gradle.kts
          ./gradlew detekt
      - name: Build
        run: ./gradlew build --parallel --scan
      - name: Test
        working-directory: ./sandbox
        run: ./gradlew build test
      - name: Version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Publish
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          VERSION: ${{ env.VERSION }}
        run: |
          echo "Publishing version ${VERSION}"
          echo "PKG_MAVEN_USERNAME ${PKG_MAVEN_USERNAME}"
          VERSION=${VERSION} make publish-libs
