name: Reusable Dev Workflow

on:
  workflow_call:
    inputs: # Define any inputs here if needed, for example, java version or branch name
      java-Version:
        description: 'Java version'
        required: false
        type: 'string'
        default: '17'
      makeDev:
        description: 'Make Command To Execute'
        required: false
        type: 'boolean'
        default: false
    secrets:
      GPG_SIGNING_KEY:
        required: true
      GPG_SIGNING_PASSWORD:
        required: true
      PKG_MAVEN_USERNAME:
        required: true
      PKG_MAVEN_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
      PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: inputs.javaVersion
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - uses: komune-io/fixers-gradle/.github/actions/setup-gradle-github-pkg@main
      - name: Lint
        run: |
          make lint
      - name: Log in to GHCR
        if: ${{ inputs.makeDev }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/komune-io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Make dev up
        if: ${{ inputs.makeDev }}
        run: make dev up
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Publish
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          VERSION: ${{ env.VERSION }}
        run: |
          echo "Publishing version ${VERSION}"
          echo "PKG_MAVEN_USERNAME ${PKG_MAVEN_USERNAME}"
          VERSION=${VERSION} make package
