name: Reusable Node.js Development Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "The version of Node.js to use."
        required: false
        type: "string"

      make-file:
        description: "The Makefile to execute."
        required: false
        type: "string"
        default: "Makefile"

      base-dir:
        description: "The base directory of the Node.js project."
        required: false
        type: "string"

      make-lint-task:
        description: "The Make command to execute for linting."
        required: false
        type: "string"
        default: "lint"

      make-build-task:
        description: "The Make command to execute for building."
        required: false
        type: "string"
        default: "build"

      make-test-env-task:
        description: "The Make command to execute for setting up the test environment."
        required: false
        type: "string"
        default: "test"

      make-test-task:
        description: "The Make command to execute for testing."
        required: false
        type: "string"
        default: "test"

      make-package-task:
        description: "The Make command to execute for packaging."
        required: false
        type: "string"
        default: "package"

      artifact-name:
        description: "The name for the uploaded artifact, if needed."
        required: false
        type: "string"

      artifact-path:
        description: "The path to the artifact to upload, if needed."
        required: false
        type: "string"

    secrets:
      NPM_AUTH_TOKEN:
        required: false

jobs:
  run-dev-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize Node.js Environment
        uses: komune-io/fixers-gradle/.github/actions/nodejs@main
        with:
          base-dir: ${{ inputs.base-dir }}
          node-version: ${{ inputs.node-version }}

      - name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version from File
        uses: komune-io/fixers-gradle/.github/actions/version@main

      - name: Execute Make Lint Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-lint-task }}

      - name: Execute Make Build Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-build-task }}

      - name: Setup Test Environment and Execute Tests
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-test-env-task }}

      - name: Execute Make Test Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-test-task }}

      - name: Execute Make Package Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-package-task }}

      - name: Upload Artifact If Specified
        if: inputs.artifact-name != '' && inputs.artifact-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
