name: Reusable Node.js Development Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "The version of Node.js to use."
        required: false
        type: "string"

      with-setup-npm-github-pkg:
        description: 'Flag to enable Npm setup with GitHub Packages.'
        required: false
        default: 'true'
        type: "string"

      with-docker-registry-login:
        description: 'Flag to enable Docker login to the Docker registry.'
        required: false
        default: 'true'
        type: "string"

      version-with-snapshot-tag:
        description: "Base directory of the Node.js project, if applicable."
        required: false
        type: "string"
        default: ".${GITHUB_SHA:0:7}"
      make-file:
        description: "The Makefile to execute."
        required: false
        type: "string"
        default: "Makefile"

      base-dir:
        description: "The base directory of the Node.js project."
        required: false
        type: "string"

      make-lint-task:
        description: "The Make command to execute for linting."
        required: false
        type: "string"
        default: "lint"

      make-build-task:
        description: "The Make command to execute for building."
        required: false
        type: "string"
        default: "build"

      make-test-task:
        description: "The Make command to execute for testing."
        required: false
        type: "string"
        default: "test"

      make-publish-task:
        description: "The Make command to execute for publishing."
        required: false
        type: "string"
        default: "publish"

      make-promote-task-condition:
        description: "The Make command to execute for promoting."
        required: false
        type: "boolean"
        default: true

      make-promote-task:
        description: "The Make command to execute for promoting."
        required: false
        type: "string"
        default: "promote"

      artifact-name:
        description: "The name for the uploaded artifact, if needed."
        required: false
        type: "string"

      artifact-path:
        description: "The path to the artifact to upload, if needed."
        required: false
        type: "string"

    secrets:
      NPM_PKG_GITHUB_TOKEN:
        required: false
      NPM_PKG_NPMJS_TOKEN:
        required: false

jobs:
  run-dev-tasks:
    runs-on: ubuntu-latest
    env:
      NPM_PKG_GITHUB_TOKEN: ${{ secrets.NPM_PKG_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize Node.js Environment
        uses: komune-io/fixers-gradle/.github/actions/nodejs@main
        with:
          base-dir: ${{ inputs.base-dir }}
          node-version: ${{ inputs.node-version }}
      - if: inputs.with-setup-npm-github-pkg == 'true'
        name: Setup Npm with GitHub Packages
        id: setup_npm_github_pkg
        uses: komune-io/fixers-gradle/.github/actions/setup-npm-github-pkg@main
        with:
          npm-auth-token: ${{ secrets.NPM_PKG_GITHUB_TOKEN }}
      - if: inputs.with-docker-registry-login == 'true'
        name: Docker Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version from File
        uses: komune-io/fixers-gradle/.github/actions/version@main
        with:
          use-snapshot: false
          with-main-pre-release-tag: '-alpha-SNAPSHOT'
          with-release-pre-release-tag: '-alpha-SNAPSHOT'
          with-snapshot-tag: ${{ inputs.version-with-snapshot-tag }}

      - name: Execute Make Lint Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-lint-task }}

      - name: Execute Make Build Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-build-task }}

      - name: Execute Make Test Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-test-task }}

      - name: Execute Make Publish Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-publish-task }}
      - name: Setup Npm with NpmJs Repository
        id: setup_npm_npmjs_pkg
        uses: komune-io/fixers-gradle/.github/actions/setup-npm-github-pkg@main
        with:
          npm-auth-token: ${{ secrets.NPM_PKG_NPMJS_TOKEN }}
          npm-registry: registry.npmjs.org
      - name: Execute Make Promote Task
        if: inputs.make-promote-task-condition || (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/'))
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-promote-task }}


      - name: Upload Artifact If Specified
        if: inputs.artifact-name != '' && inputs.artifact-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
