name: Reusable Node.js Development Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "The version of Node.js to use."
        required: false
        type: "string"

      with-setup-npm-github-pkg:
        description: 'Flag to enable Npm setup with GitHub Packages.'
        required: false
        default: 'true'
        type: "string"
      
      with-publish-docker-registry-login:
        description: 'Flag to enable Docker login to the publish Docker registry.'
        required: false
        default: 'false'
        type: "string"

      with-stage-docker-registry-login:
        description: 'Flag to enable Docker login to the stage Docker registry.'
        required: false
        default: 'true'
        type: "string"

      with-promote-docker-registry-login:
        description: 'Flag to enable Docker login to the promote Docker registry.'
        required: false
        default: 'true'
        type: "string"

      excluded-versioning-branch:
        description: "A single branch name prefix where the job should be excluded from running. For example, use 'versioning/' to skip running the job on any branch that starts with 'versioning/'."
        required: false
        type: "string"
        default: "versioning/"

      version-with-snapshot-tag:
        description: "Base directory of the Node.js project, if applicable."
        required: false
        type: "string"
        default: ".${GITHUB_SHA:0:7}"

      make-file:
        description: "The Makefile to execute."
        required: false
        type: "string"
        default: "Makefile"

      base-dir:
        description: "The base directory of the Node.js project."
        required: false
        type: "string"

      make-lint-task:
        description: "The Make command to execute for linting."
        required: false
        type: "string"
        default: "lint"

      make-build-task:
        description: "The Make command to execute for building."
        required: false
        type: "string"
        default: "build"

      make-test-task:
        description: "The Make command to execute for testing."
        required: false
        type: "string"
        default: "test"

      # DEPRECATED
      make-publish-task:
        description: "The Make command to execute for publishing."
        required: false
        type: "string"
        default: "publish"

      make-stage-task:
        description: "The Make command to execute for staging."
        required: false
        type: "string"
        default: "stage"

      make-promote-task:
        description: "The Make command to execute for promoting."
        required: false
        type: "string"
        default: "promote"

      # DEPRECATED
      docker-publish-repository:
        description: "The Docker registry to which images should be published. Defaults to GitHub Container Registry (ghcr.io)."
        required: false
        type: "string"
        default: "ghcr.io"

      docker-stage-repository:
        description: "The Docker registry to which images should be staged. Defaults to GitHub Container Registry (ghcr.io)."
        required: false
        type: "string"
        default: "ghcr.io"

      docker-promote-repository:
        description: "The Docker registry to which images should be promoted. Defaults to Docker Hub (docker.io)."
        required: false
        type: "string"
        default: "docker.io"

      docker-buildx-platform:
        description: "Specify the target platforms for Docker buildx, such as 'linux/amd64,linux/arm64'. Leave empty to use the default platform."
        required: false
        type: "string"

      artifact-name:
        description: "The name for the uploaded artifact, if needed."
        required: false
        type: "string"

      artifact-path:
        description: "The path to the artifact to upload, if needed."
        required: false
        type: "string"

      on-tag:
        description: "Comma-separated list of task names that should be executed when a tag is pushed. For example, 'lint,test,stage,promote' will run these tasks on tag events. Set to 'false' to disable all tag-specific tasks."
        required: false
        type: "string"
        default: 'false'

    secrets:
      # DEPRECATED
      DOCKER_PUBLISH_USERNAME:
        required: false
      # DEPRECATED
      DOCKER_PUBLISH_PASSWORD:
        required: false
      DOCKER_STAGE_USERNAME:
        required: false
      DOCKER_STAGE_PASSWORD:
        required: false
      DOCKER_PROMOTE_USERNAME:
        required: false
      DOCKER_PROMOTE_PASSWORD:
        required: false
      NPM_PKG_GITHUB_TOKEN:
        required: false
      NPM_PKG_NPMJS_TOKEN:
        required: false

jobs:
  run-dev-tasks:
    if: (github.event_name == 'pull_request' && !startsWith(github.head_ref, inputs.excluded-versioning-branch)) || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      NPM_PKG_GITHUB_TOKEN: ${{ secrets.NPM_PKG_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize Node.js Environment
        uses: komune-io/fixers-gradle/.github/actions/nodejs@beb8afdc4eb334c90cbada0a4a2571f17d02515d
        with:
          base-dir: ${{ inputs.base-dir }}
          node-version: ${{ inputs.node-version }}

      - if: inputs.with-setup-npm-github-pkg == 'true'
        name: Setup Npm with GitHub Packages
        id: setup_npm_github_pkg
        uses: komune-io/fixers-gradle/.github/actions/setup-npm-github-pkg@main
        with:
          npm-auth-token: ${{ secrets.NPM_PKG_GITHUB_TOKEN }}

#      # DEPRECATED
#      - if: inputs.with-publish-docker-registry-login == 'true'
#        name: Docker Registry Login
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version from File
        uses: komune-io/fixers-gradle/.github/actions/version@main
        with:
          use-snapshot: false
          with-main-pre-release-tag: '-alpha-SNAPSHOT'
          with-release-pre-release-tag: '-alpha-SNAPSHOT'
          with-snapshot-tag: ${{ inputs.version-with-snapshot-tag }}

      - name: Execute Make Lint Task
        if: (contains(inputs.on-tag, inputs.make-lint-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-lint-task }}

      - if: inputs.docker-buildx-platform != ''
        name: Setup Docker Buildx for Specified Platforms
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.docker-buildx-platform }}

      - name: Execute Make Build Task
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-build-task }}

      - name: Execute Make Test Task
        if: (contains(inputs.on-tag, inputs.make-test-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-test-task }}

      # DEPRECATED
      - if: inputs.with-publish-docker-registry-login == 'true' && ((github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'publish') && startsWith(github.ref, 'refs/tags/')) ) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'publish')))
        name: Docker Registry Login to Publish
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-publish-repository }}
          username: ${{ secrets.DOCKER_PUBLISH_USERNAME }}
          password: ${{ secrets.DOCKER_PUBLISH_PASSWORD }}

      # DEPRECATED
      - name: Execute Make Publish Task
        if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'publish') && startsWith(github.ref, 'refs/tags/')) ) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'publish'))
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-publish-task }}

      - if: inputs.with-stage-docker-registry-login == 'true' && ((github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'stage') && startsWith(github.ref, 'refs/tags/')) ) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'stage')))
        name: Docker Registry Login to Stage
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-stage-repository }}
          username: ${{ secrets.DOCKER_STAGE_USERNAME }}
          password: ${{ secrets.DOCKER_STAGE_PASSWORD }}

      - name: Execute Make Stage Task
        if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'stage') && startsWith(github.ref, 'refs/tags/')) ) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'stage'))
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-stage-task }}

      - if: inputs.with-promote-docker-registry-login == 'true' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/')))
        name: Docker Registry Login To Promote
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-promote-repository }}
          username: ${{ secrets.DOCKER_PROMOTE_USERNAME }}
          password: ${{ secrets.DOCKER_PROMOTE_PASSWORD }}

      - name: Setup Npm with NpmJs Repository
        id: setup_npm_npmjs_pkg
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/setup-npm-github-pkg@main
        with:
          npm-auth-token: ${{ secrets.NPM_PKG_NPMJS_TOKEN }}
          npm-registry: registry.npmjs.org

      - name: Execute Make Check Task
        if: (contains(inputs.on-tag, inputs.make-check-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-check-task }}

      - name: Execute Make Promote Task
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/make-step-prepost@main
        with:
          make-file: ${{ inputs.make-file }}
          make-step: ${{ inputs.make-promote-task }}

      - name: Upload Artifact if Specified
        if: inputs.artifact-name != '' && inputs.artifact-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
