name: Reusable Node.js Development Workflow (Mise)

on:
  workflow_call:
    inputs:
      node-version:
        description: "The version of Node.js to use."
        required: false
        type: "string"

      with-setup-npm-github-pkg:
        description: 'Flag to enable Npm setup with GitHub Packages.'
        required: false
        default: 'true'
        type: "string"

      with-stage-docker-registry-login:
        description: 'Flag to enable Docker login to the stage Docker registry.'
        required: false
        default: 'true'
        type: "string"

      with-promote-docker-registry-login:
        description: 'Flag to enable Docker login to the promote Docker registry.'
        required: false
        default: 'true'
        type: "string"

      excluded-versioning-branch:
        description: "A single branch name prefix where the job should be excluded from running. For example, use 'versioning/' to skip running the job on any branch that starts with 'versioning/'."
        required: false
        type: "string"
        default: "versioning/"

      version-with-snapshot-tag:
        description: "Snapshot tag suffix for versioning."
        required: false
        type: "string"
        default: ".${GITHUB_SHA:0:7}"

      base-dir:
        description: "The base directory of the Node.js project."
        required: false
        type: "string"

      mise-lint-task:
        description: "The mise task to execute for linting."
        required: false
        type: "string"
        default: "lint"

      mise-build-task:
        description: "The mise task to execute for building."
        required: false
        type: "string"
        default: "build"

      mise-test-task:
        description: "The mise task to execute for testing."
        required: false
        type: "string"
        default: "test"

      mise-stage-task:
        description: "The mise task to execute for staging."
        required: false
        type: "string"
        default: "stage"

      mise-check-task:
        description: "The mise task to execute for checking."
        required: false
        type: "string"
        default: "check"

      mise-promote-task:
        description: "The mise task to execute for promoting."
        required: false
        type: "string"
        default: "promote"

      docker-stage-repository:
        description: "The Docker registry to which images should be staged. Defaults to GitHub Container Registry (ghcr.io)."
        required: false
        type: "string"
        default: "ghcr.io"

      docker-promote-repository:
        description: "The Docker registry to which images should be promoted. Defaults to Docker Hub (docker.io)."
        required: false
        type: "string"
        default: "docker.io"

      docker-buildx-platform:
        description: "Specify the target platforms for Docker buildx, such as 'linux/amd64,linux/arm64'. Leave empty to use the default platform."
        required: false
        type: "string"

      artifact-name:
        description: "The name for the uploaded artifact, if needed."
        required: false
        type: "string"

      artifact-path:
        description: "The path to the artifact to upload, if needed."
        required: false
        type: "string"

      on-tag:
        description: "Comma-separated list of task names that should be executed when a tag is pushed."
        required: false
        type: "string"
        default: 'false'

    secrets:
      DOCKER_STAGE_USERNAME:
        required: false
      DOCKER_STAGE_PASSWORD:
        required: false
      DOCKER_PROMOTE_USERNAME:
        required: false
      DOCKER_PROMOTE_PASSWORD:
        required: false
      FIXERS_PUBLISH_NPMJS_TOKEN:
        required: false

jobs:
  run-dev-tasks:
    if: (github.event_name == 'pull_request' && !startsWith(github.head_ref, inputs.excluded-versioning-branch)) || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      FIXERS_PUBLISH_NPM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Mise
        uses: jdx/mise-action@v4

      - name: Initialize Node.js Environment
        uses: komune-io/fixers-gradle/.github/actions/nodejs@0.36.0
        with:
          base-dir: ${{ inputs.base-dir }}
          node-version: ${{ inputs.node-version }}

      - if: inputs.with-setup-npm-github-pkg == 'true'
        name: Setup Npm with GitHub Packages
        id: setup_npm_github_pkg
        uses: komune-io/fixers-gradle/.github/actions/setup-npm-github-pkg@0.36.0
        with:
          npm-auth-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version from File
        uses: komune-io/fixers-gradle/.github/actions/version@0.36.0
        with:
          use-snapshot: false
          with-main-pre-release-tag: '-alpha-SNAPSHOT'
          with-release-pre-release-tag: '-alpha-SNAPSHOT'
          with-snapshot-tag: ${{ inputs.version-with-snapshot-tag }}

      - name: Execute Mise Lint Task
        if: (contains(inputs.on-tag, inputs.mise-lint-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@0.36.0
        with:
          mise-task: ${{ inputs.mise-lint-task }}

      - if: inputs.docker-buildx-platform != ''
        name: Setup Docker Buildx for Specified Platforms
        uses: docker/setup-buildx-action@v4
        with:
          platforms: ${{ inputs.docker-buildx-platform }}

      - name: Execute Mise Build Task
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@0.36.0
        with:
          mise-task: ${{ inputs.mise-build-task }}

      - name: Execute Mise Test Task
        if: (contains(inputs.on-tag, inputs.mise-test-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@0.36.0
        with:
          mise-task: ${{ inputs.mise-test-task }}

      - if: inputs.with-stage-docker-registry-login == 'true' && ((github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'stage') && startsWith(github.ref, 'refs/tags/')) ) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'stage')))
        name: Docker Registry Login to Stage
        uses: docker/login-action@v4
        with:
          registry: ${{ inputs.docker-stage-repository }}
          username: ${{ secrets.DOCKER_STAGE_USERNAME }}
          password: ${{ secrets.DOCKER_STAGE_PASSWORD }}

      - name: Execute Mise Stage Task
        if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'stage') && startsWith(github.ref, 'refs/tags/')) ) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'stage'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@0.36.0
        with:
          mise-task: ${{ inputs.mise-stage-task }}

      - if: inputs.with-promote-docker-registry-login == 'true' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/')))
        name: Docker Registry Login To Promote
        uses: docker/login-action@v4
        with:
          registry: ${{ inputs.docker-promote-repository }}
          username: ${{ secrets.DOCKER_PROMOTE_USERNAME }}
          password: ${{ secrets.DOCKER_PROMOTE_PASSWORD }}

      - name: Setup Npm with NpmJs Repository
        id: setup_npm_npmjs_pkg
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/setup-npm-github-pkg@0.36.0
        with:
          npm-auth-token: ${{ secrets.FIXERS_PUBLISH_NPMJS_TOKEN }}
          npm-registry: registry.npmjs.org

      - name: Execute Mise Check Task
        if: (contains(inputs.on-tag, inputs.mise-check-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@0.36.0
        with:
          mise-task: ${{ inputs.mise-check-task }}

      - name: Execute Mise Promote Task
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@0.36.0
        with:
          mise-task: ${{ inputs.mise-promote-task }}

      - name: Upload Artifact if Specified
        if: inputs.artifact-name != '' && inputs.artifact-path != ''
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}