name: Reusable JVM Development Workflow (Mise)

on:
  workflow_call:
    inputs:
      java-version:
        description: "The Java version to use."
        required: false
        type: "string"
        default: "17"

      with-gradle-build-scan-publish:
        description: "Flag to enable gradle build scan publish"
        required: false
        default: true
        type: "boolean"

      with-stage-docker-registry-login:
        description: 'Flag to enable Docker login to the stage Docker registry.'
        required: false
        default: 'false'
        type: "string"

      with-promote-docker-registry-login:
        description: 'Flag to enable Docker login to the promote Docker registry.'
        required: false
        default: 'false'
        type: "string"

      excluded-versioning-branch:
        description: "A single branch name prefix where the job should be excluded from running. For example, use 'versioning/' to skip running the job on any branch that starts with 'versioning/'."
        required: false
        type: "string"
        default: "versioning/"

      mise-lint-task:
        description: "The mise task to execute for linting."
        required: false
        type: "string"
        default: "lint"

      mise-build-task:
        description: "The mise task to execute for building."
        required: false
        type: "string"
        default: "build"

      mise-test-task:
        description: "The mise task to execute for testing."
        required: false
        type: "string"
        default: "test"

      mise-stage-task:
        description: "The mise task to execute for staging."
        required: false
        type: "string"
        default: "stage"

      mise-check-task:
        description: "The mise task to execute for checking."
        required: false
        type: "string"
        default: "check"

      mise-promote-task:
        description: "The mise task to execute for promote."
        required: false
        type: "string"
        default: "promote"

      docker-buildx-platform:
        description: "Specify the target platforms for Docker buildx, such as 'linux/amd64,linux/arm64'. Leave empty to use the default platform."
        required: false
        type: "string"

      docker-stage-repository:
        description: "The Docker registry to which images should be staged. Defaults to GitHub Container Registry (ghcr.io)."
        required: false
        type: "string"
        default: "ghcr.io"

      docker-promote-repository:
        description: "The Docker registry to which images should be promoted. Defaults to Docker Hub (docker.io)."
        required: false
        type: "string"
        default: "docker.io"

      force-stage:
        description: "Flag to force execute stage task."
        required: false
        type: "string"
        default: "false"

      artifact-name:
        description: "The name for the uploaded artifact, if needed."
        required: false
        type: "string"

      artifact-path:
        description: "The path to the artifact to upload, if needed."
        required: false
        type: "string"

      on-tag:
        description: "Comma-separated list of task names that should be executed when a tag is pushed."
        required: false
        type: "string"
        default: 'false'

    secrets:
      GPG_SIGNING_KEY:
        required: false
      GPG_SIGNING_PASSWORD:
        required: false
      PKG_GITHUB_USERNAME:
        required: false
      PKG_GITHUB_TOKEN:
        required: false
      DOCKER_STAGE_USERNAME:
        required: false
      DOCKER_STAGE_PASSWORD:
        required: false
      DOCKER_PROMOTE_USERNAME:
        required: false
      DOCKER_PROMOTE_PASSWORD:
        required: false
      JRELEASER_MAVENCENTRAL_USERNAME:
        required: false
      JRELEASER_MAVENCENTRAL_PASSWORD:
        required: false
      SONAR_TOKEN:
        required: false

jobs:
  run-dev-tasks:
    if: (github.event_name == 'pull_request' && !startsWith(github.head_ref, inputs.excluded-versioning-branch)) || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
      JRELEASER_DEPLOY_MAVEN_NEXUS2_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_DEPLOY_MAVEN_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
      JRELEASER_DEPLOY_MAVEN_GITHUB_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PKG_GITHUB_USERNAME: ${{ secrets.PKG_GITHUB_USERNAME || github.actor }}
      PKG_GITHUB_TOKEN: ${{ secrets.PKG_GITHUB_TOKEN || github.token }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      FIXERS_PUBLISH_GITHUB_USERNAME: ${{ secrets.PKG_GITHUB_USERNAME || github.actor }}
      FIXERS_PUBLISH_GITHUB_TOKEN: ${{ secrets.PKG_GITHUB_TOKEN || github.token }}
      FIXERS_PUBLISH_SIGNING_GPG_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      FIXERS_PUBLISH_SIGNING_GPG_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      FIXERS_PUBLISH_MAVEN_CENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      FIXERS_PUBLISH_MAVEN_CENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Mise
        uses: jdx/mise-action@v2

      - name: Add Firefox to Run Kotlin test
        uses: browser-actions/setup-firefox@v1

      - name: Initialize Java and Gradle Environment
        uses: komune-io/fixers-gradle/.github/actions/jvm@feat/mise-action
        with:
          with-gradle-build-scan-publish: ${{ inputs.with-gradle-build-scan-publish }}
          java-version: ${{ inputs.java-version }}

      - name: Get Version from File
        uses: komune-io/fixers-gradle/.github/actions/version@feat/mise-action

      - name: Execute Mise Lint Task
        if: (contains(inputs.on-tag, inputs.mise-lint-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@feat/mise-action
        with:
          mise-task: ${{ inputs.mise-lint-task }}

      - name: Setup Docker Buildx for Specified Platforms
        if: inputs.docker-buildx-platform != ''
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.docker-buildx-platform }}

      - name: Execute Mise Build Task
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@feat/mise-action
        with:
          mise-task: ${{ inputs.mise-build-task }}

      - name: Execute Mise Test Task
        if: (contains(inputs.on-tag, inputs.mise-test-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@feat/mise-action
        with:
          mise-task: ${{ inputs.mise-test-task }}

      - name: Upload Analysis Reports
        uses: komune-io/fixers-gradle/.github/actions/upload-analysis-reports@feat/mise-action

      - name: Docker Registry Login to Stage
        if: (inputs.force-stage == 'true' || (inputs.with-stage-docker-registry-login == 'true' && ((github.ref == 'refs/heads/main' ||startsWith(github.ref, 'refs/heads/release/') ||startsWith(github.ref, 'refs/heads/versioning/') ||(contains(inputs.on-tag, 'stage') && startsWith(github.ref, 'refs/tags/'))) ||(github.event_name == 'pull_request' &&(contains(github.event.pull_request.labels.*.name, 'stage') || startsWith(github.head_ref, 'versioning/'))))))
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-stage-repository }}
          username: ${{ secrets.DOCKER_STAGE_USERNAME || github.actor }}
          password: ${{ secrets.DOCKER_STAGE_PASSWORD || github.token }}

      - name: Execute Mise Stage Task
        if: (inputs.force-stage == 'true' || (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || (contains(inputs.on-tag, 'stage') && startsWith(github.ref, 'refs/tags/'))) || (github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'stage') || startsWith(github.head_ref, 'versioning/'))))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@feat/mise-action
        with:
          mise-task: ${{ inputs.mise-stage-task }}

      - name: Execute Mise Check Task
        if: (contains(inputs.on-tag, inputs.mise-check-task) && startsWith(github.ref, 'refs/tags/')) || (!startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@feat/mise-action
        with:
          mise-task: ${{ inputs.mise-check-task }}

      - name: Docker Registry Login To Promote
        if: (inputs.with-promote-docker-registry-login == 'true' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/')) ))
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-promote-repository }}
          username: ${{ secrets.DOCKER_PROMOTE_USERNAME }}
          password: ${{ secrets.DOCKER_PROMOTE_PASSWORD }}

      - name: Execute Mise Promote Task
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ||  (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/'))
        uses: komune-io/fixers-gradle/.github/actions/mise-step-prepost@feat/mise-action
        with:
          mise-task: ${{ inputs.mise-promote-task }}

      - name: Upload Artifact if Specified
        if: inputs.artifact-name != '' && inputs.artifact-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}