name: Reusable Dev Workflow

on:
  workflow_call:
    inputs:
      storybook-dir:
        description: "Storybook base directory"
        required: false
        type: "string"

      node-version:
        description: "Node version"
        required: false
        type: "string"

      artifact-name:
        description: "Name for the uploaded artifact, leave empty if no artifact is needed"
        required: false
        type: "string"
      artifact-path:
        description: "Path to the artifact to upload, leave empty if no artifact is needed"
        required: false
        type: "string"
    secrets:
      NPM_AUTH_TOKEN:
        required: false

jobs:
  package-storybook:
    uses: komune-io/fixers-gradle/.github/workflows/make-nodejs-workflow.yml@feat/DocCi
    permissions:
      contents: read
      packages: write
    with:
      make-file: "docs.mk"
      base-dir: ${{ inputs.storybook-dir }}
      with-package-task: false
      artifact-name: storybook-static
      artifact-path: ./storybook-static
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


  publish-chromatic:
    runs-on: ubuntu-latest
    name: Publish Chromatic
    needs: [package-storybook]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Init NodeJs
        uses: komune-io/fixers-gradle/.github/actions/nodejs@feat/DocCi
        with:
          node-version: ${{ inputs.node-version }}
          base-dir: ${{ inputs.storybook-dir }}
      - uses: komune-io/fixers-gradle/.github/actions/chromatic@feat/DocCi
        with:
          artifact-name: ${{ inputs.artifact-name }}
          artifact-path: ${{ inputs.artifact-path }}

  publish-github-page:
    runs-on: ubuntu-latest
    name: Publish Github Page
    needs: [package-storybook]
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Init NodeJs
        uses: komune-io/fixers-gradle/.github/actions/nodejs@feat/DocCi
        with:
          node-version: ${{ inputs.node-version }}
          base-dir: ${{ inputs.storybook-dir }}
      - uses: komune-io/fixers-gradle/.github/actions/github-page@feat/DocCi
        with:
          artifact-name: ${{ inputs.artifact-name }}
          artifact-path: ${{ inputs.artifact-path }}
