name: Reusable Storybook Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "The Node.js version to use for the workflow."
        required: false
        type: "string"
      with-chromatic:
        description: "Determines whether to publish the Storybook to Chromatic."
        required: false
        type: "boolean"
        default: false

      with-setup-npm-github-pkg:
        description: 'Flag to enable Npm setup with GitHub Packages.'
        required: false
        default: 'false'
        type: "string"

      storybook-dir:
        description: "The base directory where the Storybook configuration resides."
        required: false
        type: "string"
        default: "storybook"

      storybook-static-dir-separator:
        description: "The directory path where the static Storybook build will be placed."
        required: false
        type: "string"
        default: "/"

      storybook-static-dir:
        description: "The directory path where the static Storybook build will be placed."
        required: false
        type: "string"
        default: "storybook-static"

    secrets:
      NPM_AUTH_TOKEN:
        required: false
      CHROMATIC_PROJECT_TOKEN:
        required: false

jobs:
  package-storybook:
    uses: komune-io/fixers-gradle/.github/workflows/make-nodejs-workflow.yml@feat/release
    with:
      make-file: "docs.mk"
      base-dir: ${{ inputs.storybook-dir }}
      artifact-name: ${{ inputs.storybook-static-dir }}
      artifact-path: ${{ inputs.storybook-dir }}${{ inputs.storybook-static-dir-separator }}${{ inputs.storybook-static-dir }}
      with-setup-npm-github-pkg: ${{ inputs.with-setup-npm-github-pkg }}
    secrets:
      NPM_PKG_GITHUB_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  publish-chromatic:
    if: inputs.with-chromatic
    runs-on: ubuntu-latest
    name: Publish to Chromatic
    needs: [package-storybook]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Initialize Node.js
        uses: komune-io/fixers-gradle/.github/actions/nodejs@feat/release
        with:
          node-version: ${{ inputs.node-version }}
          base-dir: ${{ inputs.storybook-dir }}
      - name: Publish Storybook to Chromatic
        uses: komune-io/fixers-gradle/.github/actions/chromatic@feat/release
        with:
          storybook-dir: ${{ inputs.storybook-dir }}
          storybook-static-dir: ${{ inputs.storybook-static-dir }}
          project-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  publish-github-page:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    needs: [package-storybook]
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Initialize Node.js for GitHub Pages
        uses: komune-io/fixers-gradle/.github/actions/nodejs@feat/release
        with:
          node-version: ${{ inputs.node-version }}
          base-dir: ${{ inputs.storybook-dir }}
      - name: Deploy Storybook to GitHub Pages
        uses: komune-io/fixers-gradle/.github/actions/github-page@feat/release
        with:
          artifact-name: ${{ inputs.storybook-dir }}
          artifact-path: ${{ inputs.storybook-dir }}/${{ inputs.storybook-static-dir }}
