name: Workflow Reusable - Publish Storybook

on:
  workflow_call:
    inputs:
      node-version:
        description: "The Node.js version to use for the workflow."
        required: false
        type: "string"

      with-chromatic:
        description: "Determines whether to publish the Storybook to Chromatic."
        required: false
        type: "boolean"
        default: false

      with-setup-npm-github-pkg:
        description: 'Flag to enable Npm setup with GitHub Packages.'
        required: false
        default: 'true'
        type: "string"

      base-dir:
        description: "The base directory of the Node.js project."
        required: false
        type: "string"
        default: ""

      storybook-dir:
        description: "The base directory where the Storybook configuration resides."
        required: false
        type: "string"
        default: "."

      docker-stage-repository:
        description: "The Docker registry to which images should be staged. Defaults to GitHub Container Registry (ghcr.io)."
        required: false
        type: "string"
        default: "ghcr.io"

      docker-promote-repository:
        description: "The Docker registry to which images should be promoted. Defaults to Docker Hub (docker.io)."
        required: false
        type: "string"
        default: "docker.io"

      storybook-static-dir-separator:
        description: "The directory path where the static Storybook build will be placed."
        required: false
        type: "string"
        default: "/"

      storybook-static-dir:
        description: "The directory path where the static Storybook build will be placed."
        required: false
        type: "string"
        default: "storybook-static"

      on-tag:
        description: "Comma-separated list of task names that should be executed when a tag is pushed. Set to 'false' to disable all tag-specific tasks."
        required: false
        type: "string"
        default: 'false'

      make-file:
        description: "The Makefile to execute."
        required: false
        type: "string"
        default: "make_docs.mk"

    secrets:
      FIXERS_CHROMATIC_PROJECT_TOKEN:
        required: false
      DOCKER_STAGE_USERNAME:
        required: false
      DOCKER_STAGE_PASSWORD:
        required: false
      DOCKER_PROMOTE_USERNAME:
        required: false
      DOCKER_PROMOTE_PASSWORD:
        required: false

jobs:
  package-storybook:
    uses: komune-io/fixers-gradle/.github/workflows/make-nodejs-workflow.yml@0.36.0
    with:
      make-file: ${{ inputs.make-file }}
      base-dir: ${{ inputs.base-dir }}
      artifact-name: ${{ inputs.storybook-static-dir }}
      artifact-path: ${{ inputs.storybook-dir }}${{ inputs.storybook-static-dir-separator }}${{ inputs.storybook-static-dir }}
      with-setup-npm-github-pkg: ${{ inputs.with-setup-npm-github-pkg }}
      docker-stage-repository: ${{ inputs.docker-stage-repository }}
      docker-promote-repository: ${{ inputs.docker-promote-repository }}
      on-tag: ${{ inputs.on-tag }}
    secrets:
      DOCKER_STAGE_USERNAME: ${{ secrets.DOCKER_STAGE_USERNAME }}
      DOCKER_STAGE_PASSWORD: ${{ secrets.DOCKER_STAGE_PASSWORD }}
      DOCKER_PROMOTE_USERNAME: ${{ secrets.DOCKER_PROMOTE_USERNAME }}
      DOCKER_PROMOTE_PASSWORD: ${{ secrets.DOCKER_PROMOTE_PASSWORD }}

  publish-chromatic:
    if: inputs.with-chromatic
    runs-on: ubuntu-latest
    name: Publish to Chromatic
    needs: [package-storybook]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Initialize Node.js
        uses: komune-io/fixers-gradle/.github/actions/nodejs@0.36.0
        with:
          node-version: ${{ inputs.node-version }}
          base-dir: ${{ inputs.base-dir }}
      - name: Publish Storybook to Chromatic
        uses: komune-io/fixers-gradle/.github/actions/chromatic@0.36.0
        with:
          storybook-dir: ${{ inputs.storybook-dir }}
          storybook-static-dir: ${{ inputs.storybook-static-dir }}
          storybook-static-dir-separator: ${{ inputs.storybook-static-dir-separator }}
          project-token: ${{ secrets.FIXERS_CHROMATIC_PROJECT_TOKEN }}

  publish-github-page:
    if: github.ref == 'refs/heads/main' || (contains(inputs.on-tag, 'promote') && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    needs: [package-storybook]
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Initialize Node.js for GitHub Pages
        uses: komune-io/fixers-gradle/.github/actions/nodejs@0.36.0
        with:
          node-version: ${{ inputs.node-version }}
          base-dir: ${{ inputs.base-dir }}
      - name: Deploy Storybook to GitHub Pages
        uses: komune-io/fixers-gradle/.github/actions/github-page@0.36.0
        with:
          artifact-name: ${{ inputs.storybook-static-dir }}
          artifact-path: ${{ inputs.storybook-dir }}${{ inputs.storybook-static-dir-separator }}${{ inputs.storybook-static-dir }}
